cmake_minimum_required(VERSION 3.18)
project(ComparisonAsioEcho LANGUAGES CXX)
find_path(ASIO_INCLUDE_DIR asio.hpp REQUIRED)
find_package(Threads REQUIRED)
add_executable(asio-echo main.cpp)
target_compile_features(asio-echo PRIVATE cxx_std_20)
target_compile_definitions(asio-echo PRIVATE ASIO_STANDALONE)
target_include_directories(asio-echo SYSTEM PRIVATE "${ASIO_INCLUDE_DIR}")
target_link_libraries(asio-echo PRIVATE Threads::Threads)
include(GNUInstallDirs)
install(TARGETS asio-echo RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR})
